packages:
  - packages/*
  - apps/*
  - plugins/*
  - internal/components
ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - sharp
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - just-pnpm
  - style-dictionary
useNodeVersion: 22.17.0
