name: Check CLI node compatibility
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/cli'

permissions:
  contents: read

jobs:
  check-cli-node-compatibility:
    name: Check CLI Node Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/gh-setup
      - name: Install Dependencies
        run: pnpm install
      - name: Build CLI (Node ${{ matrix.node-version }})
        run: pnpm build:cli
      - name: Test CLI (Node ${{ matrix.node-version }})
        run: pnpm test:cli
