name: Checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'plugins/**'
      - 'biome.jsonc'

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - name: Types
        run: pnpm types
      - name: Biome CI
        run: pnpm biome ci .
