name: Deploy www
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: next
        description: Deploy to environment
        options:
          - production
          - next
  push:
    branches:
      - main
    paths:
      - 'apps/www/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-production:
    uses: ./.github/workflows/azure-deploy-www.yml
    with:
      environment: ${{ github.event.inputs.environment == 'production' && 'production' || 'preview' }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
