name: Deploy Themebuilder
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: next
        description: Deploy to environment
        options:
          - production
          - next
  push:
    branches:
      - main
    paths:
      - 'apps/themebuilder/**'

jobs:
  deploy-production:
    uses: ./.github/workflows/vercel-deploy-theme.yml
    with:
      environment: ${{ github.event.inputs.environment == 'production' && 'production' || 'preview' }}
      vercel_alias: ${{ github.event.inputs.environment != 'production' && 'next.theme.designsystemet.no' || '' }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID_THEMEBUILDER: ${{ secrets.VERCEL_PROJECT_ID_THEMEBUILDER }}
