name: Deploy www Preview
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/www/**'

jobs:
  deploy-preview:
    uses: ./.github/workflows/vercel-deploy-www.yml
    with:
      environment: preview
      pr_number: ${{ github.event.number }}
      update_comment: true
      vercel_alias: pr-${{ github.event.number }}.designsystemet.no
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID_WWW: ${{ secrets.VERCEL_PROJECT_ID_WWW }}
