name: Preview Cleanup

on:
  pull_request:
    types: [closed]

env:
  VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
  STORYBOOK_URL: pr-${{ github.event.number }}.storybook.designsystemet.no
  THEME_URL: pr-${{ github.event.number }}.theme.designsystemet.no
  WWW_URL: pr-${{ github.event.number }}.www.designsystemet.no
  ALIASES: ''

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - id: get-aliases
        name: Get a list of all Vercel aliases and set it to ENV
        run: |
          {
            echo 'ALIASES<<EOF'
            vercel alias ls --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} --limit 20
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Remove Storybook alias if it exists
        if: contains(env.ALIASES, env.STORYBOOK_URL)
        run: vercel alias rm --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} ${{ env.STORYBOOK_URL }}

      - name: Remove Theme alias if it exists
        if: contains(env.ALIASES, env.THEME_URL)
        run: vercel alias rm --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} ${{ env.THEME_URL }}

      - name: Remove WWW alias if it exists
        if: contains(env.ALIASES, env.WWW_URL)
        run: vercel alias rm --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} ${{ env.WWW_URL }}
