name: Deploy www Preview
env:
  VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WWW }}
  PR_NUMBER: ${{ github.event.number }}
  VERCEL_ENV: ${{ github.event.inputs.environment == 'production' && 'production' || 'preview' }}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/www/**'
jobs:
  Deploy-Preview:
    if: ${{ github.repository == 'digdir/designsystemet' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - name: Use node 22 and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - id: deploy
        name: Deploy Project Artifacts to Vercel
        run: echo "url=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

      - name: Set Vercel alias
        run: vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }} set ${{ steps.deploy.outputs.url }} pr-${{ env.PR_NUMBER }}.designsystemet.no

      - name: Find Preview Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body-includes: |
            **Preview deployments for this pull request:**

      - run: echo ${{ steps.fc.outputs.comment-id }}
        if: success() && env.PR_NUMBER

      - name: Find Storybook deployment
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-storybook
        with:
          text: ${{ steps.fc.outputs.comment-body }}
          regex: '\[Storybook\]\((https:\/\/[^)]+)\).*'

      - name: Find Theme deployment
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-theme
        with:
          text: ${{ steps.fc.outputs.comment-body }}
          regex: '\[theme\]\((https:\/\/[^)]+)\).*'

      - name: Get current time in CEST
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: D. MMM YYYY - HH:mm
          timezone: Europe/Oslo

      - name: Update comment with deployment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Preview deployments for this pull request:**

            ${{ steps.regex-storybook.outputs.match }}

            ${{ steps.regex-theme.outputs.match }}

            [www](https://pr-${{ env.PR_NUMBER }}.designsystemet.no) - `${{ steps.current-time.outputs.formattedTime }}`
