# https://github.com/anthonyhastings/turborepo-design-system
name: Release Snapshot

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'npm tag'
        type: choice
        default: 'test'
        options:
          - next
          - test

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  snapshot:
    name: Snapshot Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - id: snapshot
        name: Set Snapshot Name
        run: |
          NAME="${{ github.ref_name }}"
          NAME="${NAME//\//-}"
          echo "name=${NAME}" >> $GITHUB_OUTPUT
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Snapshot Release
        run: |
          pnpm run version-packages --snapshot "${{ steps.snapshot.outputs.name }}"
          echo '---'
          echo 'Detected Changes:'
          git diff
          echo '---'
          pnpm run publish-packages --tag "${{ github.event.inputs.tag }}" --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
