name: Visual tests
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
    branches: [main, next]
    types: [ready_for_review, synchronize, opened]
    paths:
      - .github/workflows/visual-tests.yml
      - 'packages/**/*.@(tsx|ts)'
      - 'packages/**/*.css'
      - 'packages/**/*.stories.@(ts|tsx)'
      - 'apps/storybook/**'
      - 'design-tokens/**/*.(json|jsonc)'

concurrency:
  group: test-visual-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: Build & run visual/interaction tests
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.repository == 'digdir/designsystemet' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Necessary for Chromatic
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - name: Build storybook
        run: pnpm build:storybook
      - name: Run Chromatic (visual and interaction tests)
        uses: chromaui/action@latest
        with:
          workingDir: apps/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: '{main,next}'
          onlyChanged: true
          skip: '@(renovate/**|dependabot/**)'
