name: Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - 'packages/**'
      - 'apps/storybook/**'

permissions:
  checks: write
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - name: Types
        run: pnpm types:react

      - name: Test
        run: pnpm test
      - name: 'Report Coverage'
        if: success() || failure()
        uses: davelosert/vitest-coverage-report-action@v2
      - name: Publish unit test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'test-report.xml'
          detailed_summary: true
          check_name: Unit Test Report
          check_annotations: true
          check_title_template: '{{FILE_NAME}} / {{TEST_NAME}}'

      - name: Test CLI (create tokens, then build the theme)
        run: pnpm test:cli

      - name: Install playwright and run Storybook tests
        run: pnpm test:storybook
      - name: Replace relative paths in test report
        uses: jacobtomlinson/gha-find-replace@v3
        if: success() || failure()
        with:
          include: 'apps/storybook/test-report.xml'
          find: '../../'
          replace: ''
          regex: false
      - name: Publish Storybook test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'apps/storybook/test-report.xml'
          detailed_summary: true
          check_name: Storybook Test Report
          check_annotations: true
          check_title_template: '{{FILE_NAME}} / {{TEST_NAME}}'
