name: Visual tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main, next]
    types:
      # Ensure workflow is run when PR is ready for review
      - ready_for_review
      # Also enable the default trigger types, for instances when
      # the PR is not opened as a draft first
      - opened
      - reopened
      - synchronize

    paths:
      - .github/workflows/visual-tests.yml
      - 'packages/**'
      - 'apps/storybook/**'
  push:
    branches: [main, next]

jobs:
  checks:
    name: Build & run visual/interaction tests
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.repository == 'digdir/designsystemet' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Necessary for Chromatic
          fetch-depth: 0
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - name: Build storybook
        run: pnpm build:storybook
      - name: Run Chromatic (visual and interaction tests)
        uses: chromaui/action@latest
        with:
          workingDir: apps/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: '{main,next}'
