name: Visual tests

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
    branches: [main, next]
    types: [ready_for_review, synchronize, opened]
    paths:
      - .github/workflows/visual-tests.yml
      - 'packages/**/*.@(tsx|ts)'
      - 'packages/**/*.css'
      - 'packages/**/*.stories.@(ts|tsx)'
      - 'apps/storybook/**'
      - 'design-tokens/**/*.(json|jsonc)'

concurrency:
  group: test-visual-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  fail_if_pull_request_is_draft:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == true }}
    runs-on: ubuntu-latest
    steps:
      - name: pr is draft → fail fast
        run: exit 1

  checks:
    name: Build & run visual/interaction tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          # Necessary for Chromatic
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: pnpm build
      - name: Build storybook
        run: pnpm build:storybook
      - name: Run Chromatic (visual and interaction tests)
        uses: chromaui/action@latest # wants us to always use latest https://github.com/chromaui/action
        with:
          workingDir: apps/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: '{main,next}'
          onlyChanged: true
          skip: '@(renovate/**|dependabot/**)'
